package main

import (
	"github.com/gin-gonic/gin"
	swaggerFiles "github.com/swaggo/files"
	ginSwagger "github.com/swaggo/gin-swagger"
	"github.com/tschechniker/goCloud/controllers"
	_ "github.com/tschechniker/goCloud/docs" // docs is generated by Swag CLI, you have to import it.
	"github.com/tschechniker/goCloud/models"
)

func setupRoutes() *gin.Engine {
	r := gin.Default()
	r.GET("/swagger/*any", ginSwagger.WrapHandler(swaggerFiles.Handler, ginSwagger.URL("http://localhost:8080/swagger/doc.json")))

	v1 := r.Group("/v1")
	{
		v1.GET("/files", controllers.FindFiles)
	}
	return r
}

// @title Go Cloud
// @version 0.1
// @description Simple cloud storage server written in go
// @termsOfService http://swagger.io/terms/

// @contact.name API Support
// @contact.url http://www.swagger.io/support
// @contact.email support@swagger.io

// @license.name Apache 2.0
// @license.url http://www.apache.org/licenses/LICENSE-2.0.html

// @host petstore.swagger.io
// @BasePath /v1

func main() {
	r := setupRoutes()
	models.ConnectDatabase()
	r.Run()
}
